params:
  epoch: 1
  batch_size: 32
  no_classes: 10
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000

artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plots_dir: plot
  checkpoints_dir: checkpoint

logs:
  logs_dir: logs_dir
  genral_dir: genral
  tensorboard_logs: tensorboard_logs
